# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage-web-api.fullname" . }}
  labels:
    {{- include "storage-web-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "storage-web-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- range $key, $val := .Values.podAnnotations }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
      labels:
        aadpodidbinding: {{ .Values.podPrincipalName }}
        {{- include "storage-web-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:          
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
